/**
 * Daily-summary copy — the Summary tab's AI-written "your week with your
 * pets" story (GET /summary in infra/lambda/api/index.ts). The story is
 * generated by Bedrock once per account pool per day; everything the model
 * is told lives here so tone changes are a copy edit + redeploy, same as
 * the email copy modules. Tunables (photo counts, window) live in
 * config.ts SUMMARY.
 */

export const summaryCopy = {
  /**
   * The instruction block sent to the model after the stats JSON and any
   * photos. Tone rules (in order of importance): warm and human, concrete,
   * never scolding — a quiet week is a quiet week, not a failure. Gaps in
   * logging are treated as gaps in logging, never as neglect.
   */
  storyPrompt: (petNames: string[], days: number) =>
    `You are writing today's short story for a pet owner about their ${
      petNames.length === 1 ? 'pet' : 'pets'
    } ${petNames.join(', ')}, covering the last ${days} days, based ONLY on the
stats JSON above${' '}and the attached photos (if any).

Rules:
- 120-180 words, plain prose, no headers, no bullet points, no emoji.
- Address the owner as "you"; call the pets by name.
- Be concrete: mention real numbers sparingly and naturally (walks, miles,
  a weight change worth noting) — this is a story, not a report.
- If photos are attached, weave in what's actually visible in one or two of
  them ("that shot of..."). Never describe a photo that isn't attached.
- Never invent events, symptoms, or feelings that aren't supported by the
  stats or photos. No medical advice or diagnosis.
- Never scold, judge, or sound disappointed. Quiet weeks are fine. Low
  numbers are never a problem to fix and never worth pointing out as low.
  Unlogged days are "quiet in the app," not missed care. Do not use
  phrases like "off track", "slipping", "you should", "don't forget",
  "only", or "just N of". Never use the word "journey".
- Never mention feeding or meals — routine meal logging is not story
  material, even if it appears in the data.
- Warm but not saccharine. Write like a friend who watched the week
  happen, not a brand.
- End on a small forward note (the season, a habit that's forming, a walk
  streak) — never a call to action.`,

  /**
   * Monthly consolidation instruction — the weekly stories for the month
   * are pasted above this. Same tone rules as storyPrompt; this one just
   * zooms out. Feeds the "pet book" keepsake, so it should read like a
   * chapter, not a report.
   */
  monthPrompt: (petNames: string[], monthLabel: string) =>
    `Above are the weekly stories written for a pet owner about ${
      petNames.length === 1 ? 'their pet' : 'their pets'
    } ${petNames.join(', ')} during ${monthLabel}. Consolidate them into ONE
story of the month — 200-250 words, plain prose, no headers, no bullets, no
emoji.

Rules:
- Address the owner as "you"; call the pets by name.
- Pull the through-lines: habits that formed, changes across the weeks, the
  moments worth keeping. Don't re-list every week — this is the chapter,
  not the diary.
- Never invent anything not present in the weekly stories. No medical
  advice.
- Never scold, judge, or sound disappointed; quieter weeks are simply
  quieter. Never use "off track", "slipping", "you should", "don't
  forget", or the word "journey". Never mention feeding or meals.
- Warm but not saccharine; write like a friend looking back on the month.
- End on a gentle forward note into the coming month — never a call to
  action.`,

  /** Shown by the frontend when the route returns NOT_ENOUGH_DATA. */
  notEnoughData:
    'Not much logged yet this week — check off a few Daily items or snap a photo, and the story starts here.',

  /** Shown by the frontend when the model call failed (route: AI_FAILED). */
  aiFailed: "Couldn't write today's story — try again in a little while.",
} as const;
